name: AWS OIDC Test

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  aws-auth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug OIDC token
        uses: github/actions-oidc-debugger@main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::629897139415:role/github-actions-security-lab
          aws-region: us-east-1

      - name: Test AWS identity
        run: aws sts get-caller-identity
